version: '3'
services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=database
      - DB_PORT=27017
      - DB_NAME=test
      - DB_USERNAME=
      - DB_PASSWORD=
    depends_on:
      - database
  database:
    image: mongo